version: "3"
services:
  web:  
    build: ./app
    ports:
      - "8081:8080"
    external_links:
      - sod_db
    networks:
      - default
      - sod_default

  db:  
    build: ./db
    ports:
      - "4642:5432"
    volumes:
      - sod-data:/var/lib/postgresql/data
    networks:
      - default
      - sod_default

volumes:
  sod-data:  

networks:
  sod_default:
    external: true
